# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - result

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
          containerRegistry: 'dockerhub'
          repository: 'resultapp'
          command: 'build'
          Dockerfile: '**/result/Dockerfile'
          tags: '$(tag)'
- stage: Push
  displayName: Push the image
  jobs:
  - job: Push
    displayName: Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Push the image to dockerhub
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'resultapp'
        command: 'push'
        tags: '$(tag)'
         

